package instincts

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// DraftBannerPrefix is the leading line in every draft generated by `fdh evolve`.
// CI of the hub blocks PRs that try to merge a SKILL.md still containing this banner.
const DraftBannerPrefix = "> ⚠️ DRAFT"

// DraftBanner is the full banner text. Replaced when the admin curates the draft.
func DraftBanner(generatedAt time.Time, command string) string {
	return fmt.Sprintf(
		"%s — generated by `fdh evolve` at %s by command `%s`. "+
			"Review TODOs and remove this banner before opening a PR to the hub.",
		DraftBannerPrefix,
		generatedAt.UTC().Format(time.RFC3339),
		command,
	)
}

// DraftOptions controls draft generation.
type DraftOptions struct {
	// GeneratedAt is stamped on the draft for traceability. Use time.Now() in production.
	GeneratedAt time.Time

	// EvolveCommand is the exact `fdh evolve ...` command that produced the draft.
	EvolveCommand string
}

// Slug returns a deterministic slug derived from domain + top keywords.
// Suitable as the skill name and the output directory under fdh-evolve-output/.
func (c *Cluster) Slug() string {
	parts := []string{strings.ToLower(c.Domain)}
	for i, k := range c.Keywords {
		if i >= 3 {
			break
		}
		parts = append(parts, strings.ToLower(k))
	}
	slug := strings.Join(parts, "-")
	slug = slugNonAlpha.ReplaceAllString(slug, "-")
	slug = strings.Trim(slug, "-")
	if slug == "" {
		slug = "untitled-cluster"
	}
	return slug
}

var slugNonAlpha = regexp.MustCompile(`[^a-z0-9-]+`)

// RenderDraft produces the SKILL.md body for a cluster, ready to write to disk.
func (c *Cluster) RenderDraft(opts DraftOptions) string {
	if opts.GeneratedAt.IsZero() {
		opts.GeneratedAt = time.Now()
	}
	var b strings.Builder

	// Banner first — CI of the hub detects this and blocks merges.
	fmt.Fprintln(&b, DraftBanner(opts.GeneratedAt, opts.EvolveCommand))
	fmt.Fprintln(&b)

	// Frontmatter (partial). Admin must complete agents_supported + min_fdh_version.
	fmt.Fprintln(&b, "---")
	fmt.Fprintf(&b, "name: %s\n", c.Slug())
	fmt.Fprintln(&b, "kind: skill")
	fmt.Fprintln(&b, "description: 'TODO: replace with a one-line summary derived from the sourced instincts.'")
	fmt.Fprintln(&b, "owner_team: 'TODO: assign owning team'")
	if len(c.Tags) > 0 {
		fmt.Fprintf(&b, "tags: [%s]\n", strings.Join(quote(c.Tags), ", "))
	} else {
		fmt.Fprintln(&b, "tags: []")
	}
	fmt.Fprintln(&b, "default: false")
	fmt.Fprintln(&b, "min_fdh_version: '0.4.0'  # TODO: confirm")
	fmt.Fprintln(&b, "agents_supported: [claude-code]  # TODO: review agents this applies to")
	fmt.Fprintf(&b, "path: skills/%s\n", c.Slug())
	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)

	// Title.
	fmt.Fprintf(&b, "# %s\n\n", titleCase(c.Slug()))

	// Sourced from (traceability).
	fmt.Fprintln(&b, "## Sourced from (generated by `fdh evolve`)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- Generated at: %s\n", opts.GeneratedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "- Command: `%s`\n", opts.EvolveCommand)
	fmt.Fprintf(&b, "- Cluster avg confidence: %.2f\n", c.AvgConfidence)
	fmt.Fprintf(&b, "- Domain: `%s`\n", c.Domain)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Source instincts:")
	fmt.Fprintln(&b)
	members := make([]*Instinct, len(c.Members))
	copy(members, c.Members)
	sort.Slice(members, func(i, j int) bool { return members[i].ID < members[j].ID })
	for _, m := range members {
		fmt.Fprintf(&b, "- `%s` (%s, confidence %.2f, captured %s by %s) — %s\n",
			m.ID,
			m.Domain,
			m.Confidence,
			m.CapturedAt.UTC().Format("2006-01-02"),
			m.CapturedBy,
			m.Title,
		)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Inspect a source with: `fdh instinct show <id>`.")
	fmt.Fprintln(&b)

	// Placeholder sections.
	fmt.Fprintln(&b, "## Purpose")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "TODO: write a one-paragraph statement of what this skill enables.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Rules")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "TODO: distill the source instincts into 3–8 normative rules.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## How to apply")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "TODO: explain when an agent should load this skill and what behaviour it should produce.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Source bodies (verbatim)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "<details><summary>Click to expand original instinct bodies — useful while curating, remove before merging</summary>")
	fmt.Fprintln(&b)
	for _, m := range members {
		fmt.Fprintf(&b, "### `%s` — %s\n\n", m.ID, m.Title)
		fmt.Fprintln(&b, strings.TrimSpace(m.Body))
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "</details>")
	return b.String()
}

// OutputPath returns the on-disk path where RenderDraft's output should land,
// rooted at the given directory (typically `./fdh-evolve-output/`).
func (c *Cluster) OutputPath(rootDir string) string {
	return filepath.Join(rootDir, c.Slug(), "SKILL.md")
}

// HasDraftBanner returns true if the given Markdown content still contains
// the `fdh evolve` draft banner. Used by CI of the hub to block PRs that
// merge an un-curated draft.
func HasDraftBanner(content string) bool {
	return strings.Contains(content, DraftBannerPrefix)
}

func quote(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "'" + strings.ReplaceAll(s, "'", "''") + "'"
	}
	return out
}

func titleCase(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}
