// Ambient declarations not regenerated by Next.

declare module "*.css";

// The `server-only` marker package ships no type declarations and no `types`
// export condition, so `tsc` (moduleResolution: bundler) cannot resolve the
// side-effect import `import "server-only"` in lib/bff.ts. It exports nothing —
// its only purpose is to make a build fail if pulled into a Client Component.
// This ambient declaration lets the typecheck pass without weakening the guard
// (the real runtime/bundler behavior is unchanged).
declare module "server-only";
